# Generated by Django 4.1 on 2022-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='altitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pole',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
